[[redirects]]
from = "/events/event-number-3/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"

[[redirects]]
from = "/events/event-number-2/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"

[[redirects]]
from = "/events/event-number-1/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"
